name: Front deploy
on:
  push:
    paths-ignore:
      - '!packages/admin/**'
    branches:
      - master

jobs:
  release:
    name: Compiling a new frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-platform --frozen-lockfile
      - run: yarn build
        working-directory: ./packages/front
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./packages/front/dist/ssr
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          path: ./packages/front/dist/ssr/www
          destination: cdn.openfortravel.org
